### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Githubman6996** [CryptoDude3/blooket-bot#2]
Site won’t load

**Comment by Githubman6996** [comment]
@CryptoDude3

**Comment by Githubman6996** [comment]
<img width="375" alt="httpsblooketbot glitch me" src="https://github.com/CryptoDude3/blooket-bot/assets/144396091/be9f4e21-c870-4507-a9b0-86bfa5324f51">

**Comment by Githubman6996** [comment]
It's working now

**Comment by Githubman6996** [comment]
Sorry accidentally closed it @CryptoDude3

**Comment by Githubman6996** [comment]
failed to start application on blooketbot.glitch.me

This is most likely because your project has a code error.
Check your project logs, fix the error and try again.

**Comment by CryptoDude3** [comment]
Ik I'm gonna fix it tommorow once and for all. Glitch has been being really
weird lately
